<?php

/**
 * TekstTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TekstTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TekstTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tekst');
    }
}