<?php

/**
 * Tekst
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    clipboard
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tekst extends BaseTekst
{
    public static function doSelect(Criteria $criteria){
        $criteria = clone $criteria;
        $criteria->addAscendingOrderByColumn(self::NAME);
        return parent::doSelect($criteria);
    }
}