options:
  collate: utf8_polish_ci
  charset: utf8
  type: InnoDB


Tekst:
  options:
    collate: utf8_polish_ci
    charset: utf8
    type: InnoDB
  actAs:
    Timestampable:
  columns:
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    contents:
      type: string(4096)
    nazwa:
      type: string(128)
    autor: string(256)
    skrot: string(128)
  